---
title: "package-sources"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{package-sources}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Package Sources

Packages can be installed from a number of locations. The {updateme}
package seeks to examine the original source of a package for newer
versions at load-time:

-   E.g. if you installed a package from CRAN using
    `install.packages()`, CRAN will be checked for newer versions (using
    `available.packages()`)

-   E.g. if you installed a package from GitHub using `pak::pak()`,
    GitHub will be checked for newer versions

It may be that, say, after installing a package from CRAN, you want to
{updateme} to check GitHub for possible updates. This is
configurable.... .........

## Source detection mechanisms

| Package source | Source detection mechanism       | New version detection mechanism | Notes                                                                                                                                                 |
|-----------------|-----------------|-----------------|----------------------|
| CRAN           | `DESCRIPTION` field `Repository` | `available.packages()`          |                                                                                                                                                       |
| GitHub         |                                  |                                 | It is assumed that GitHub packages are installed using either {pak} or {remotes}. Other methods of installation may not work properly with {updateme} |
|                |                                  |                                 |                                                                                                                                                       |
|                |                                  |                                 |                                                                                                                                                       |
|                |                                  |                                 |                                                                                                                                                       |
|                |                                  |                                 |                                                                                                                                                       |
|                |                                  |                                 |                                                                                                                                                       |
|                |                                  |                                 |                                                                                                                                                       |
|                |                                  |                                 |                                                                                                                                                       |
|                |                                  |                                 |                                                                                                                                                       |

| Source                      | Method                    | Field: Repository |     |     |
|---------------|---------------|---------------|---------------|---------------|
| CRAN                        | install.packages()        | CRAN              |     |     |
|                             | pak::pak()                |                   |     |     |
|                             | BiocManager::install()    |                   |     |     |
| CRAN-like (e.g. r-universe) | install.packages()        |                   |     |     |
|                             | pak::pak()                |                   |     |     |
|                             | BiocManager::install()    |                   |     |     |
| GitHub                      | pak::pak()                |                   |     |     |
|                             | remotes::install_github() |                   |     |     |
| GitLab                      | pak::pak()                |                   |     |     |
|                             | remotes::install_gitlab() |                   |     |     |
| Git (any)                   | pak::pak()                |                   |     |     |
|                             | remotes::install_git()    |                   |     |     |
| Bioc                        | pak::pak()                |                   |     |     |
|                             | BiocManager::install()    |                   |     |     |
| Local (?)                   | devtools::install()       |                   |     |     |

## CRAN / install.packages()

```
Repository: CRAN
Date/Publication: 2023-09-27 09:20:06 UTC
Built: R 4.3.1; aarch64-apple-darwin20; 2023-09-27 11:18:47 UTC; unix
Archs: lubridate.so.dSYM
```

## CRAN / pak::pak()
```
Repository: CRAN
Date/Publication: 2023-09-27 09:20:06 UTC
Built: R 4.3.1; aarch64-apple-darwin20; 2023-09-27 11:18:47 UTC; unix
Archs: lubridate.so.dSYM
RemoteType: standard
RemotePkgRef: lubridate
RemoteRef: lubridate
RemoteRepos: https://cran.rstudio.com/
RemotePkgPlatform: aarch64-apple-darwin20
RemoteSha: 1.9.3
```
